spring:
  application:
    name: search
  datasource:
    url: jdbc:h2:mem:mydb;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        errorDecoder: com.hue.search.client.configuration.ClientErrorDecoder
      kakao:
        default-request-headers:
          Authorization:
            - KakaoAK e6f8e294bdf1e464848f4ab2f01ebcae
      naver:
        default-request-headers:
          X-Naver-Client-Id:
            - U2pIrryJ2iVXoFLfNreY
          X-Naver-Client-Secret:
            - PqYR5xnHaW

logging:
  file.path: /tmp
  level:
    com.hue.search: debug
