spring:
  application:
    name: search
  datasource:
    url: jdbc:h2:mem:mydb;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console


feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        default-request-headers:
          Authorization:
            - KakaoAK ${REST_API_KEY}

logging:
  file.path: /tmp
  level:
    com.hue.search: debug
